spring:  
  application:
    name: customer-service
  jackson:
    deserialization:
      fail-on-unknown-properties: false

server:  
  port: ${PORT:8092}
  
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      
---
spring:
  profiles: dev
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: customer
      username: micro 
      password: micro123

---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 27017      

---
spring:
  profiles: no-discovery
eureka:
  client:
    enabled: false
ribbon:
  eureka:
    enable: false
  listOfServers: account-service:8080
  