spring:  
  application:
    name: order-service

server:  
  port: ${PORT:8090}

 
---
spring:
  profiles: dev
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: micro
      username: micro 
      password: micro123

---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 27017      

---
spring:
  profiles: no-discovery
eureka:
  client:
    enabled: false
account-service:
  ribbon:
    eureka:
      enable: false
    listOfServers: account-service:8080
customer-service:
  ribbon:
    eureka:
      enable: false
    listOfServers: customer-service:8080
product-service:
  ribbon:
    eureka:
      enable: false
    listOfServers: product-service:8080