spring:  
  application:
    name: product-service

server:  
  port: ${PORT:8093}
  
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
       
---
spring:
  profiles: dev
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: product
      username: micro
      password: micro123

---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 27017 

---
spring:
  profiles: no-discovery     
eureka:
  client:
    enabled: false