spring:  
  application:
    name: account-service
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      database: micro
      username: micro 
      password: micro123
      
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    
---
spring:
  profiles: zone1
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      preferSameZoneEureka: true
server:  
  port: ${PORT:8091}

---
spring:
  profiles: zone2
eureka:
  instance:
    metadataMap:
      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      preferSameZoneEureka: true
server:  
  port: ${PORT:9091}